import Navbar from "../components/Navbar";
import Head from "next/head";
import Link from "next/link";
import { projectsdata as projects } from "../lib/data";

const Projects = () => {
  return (
    <>
      <Head>
        <title>DK | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Navbar />
      <div className="bg-repeat w-full h-full heropattern-circuitboard-purple-200 p-5">
        <div className="bg-accent-focus text-primary font-serif  bg-opacity-100 border-2 border-primary rounded-2xl p-6 my-20 mx-auto">
          <h1 className="lg:text-7xl text-5xl mb-0 pb-0 colorful font-bold mx-auto text-center ">
            <span>Projects</span>
          </h1>
          <p className="text-xl mt-3 text-center">
            A selection of my projects available for demonstration.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-4 lg:gap-12">
          {projects.map((project, idx) => (
            <div
              key={idx}
              className="card bg-base-100 shadow-lg hover:shadow-xl hover:scale-105 border border-primary rounded-lg"
            >
              <div className="rounded shadow-lg">
                <div className="flex flex-column flex-1">
                  <img
                    layout="fill"
                    className="w-full h-48 object-cover"
                    src={project.image}
                    alt={project.title}
                    quality="100"
                  />
                </div>
              </div>
              <div className="card-body items-center">
                <h2 className="card-title hover:underline">
                  {project.title.toUpperCase()}
                </h2>
                <div className="badge badge-primary truncate hover:cursor-default">
                  {project.type.toUpperCase()}
                </div>
                <p className="mb-2">{project.description}</p>
                <div className="card-actions mb-6 ">
                  {project.subtitle.split(",").map((item, idxt) => (
                    <div
                      key={idxt}
                      className="badge badge-outline hover:cursor-default mx-auto"
                    >
                      {item.toUpperCase()}
                    </div>
                  ))}
                </div>
                <div>
                  <div className="badge badge-accent border border-primary mr-2 hover:border-secondary hover:scale-125">
                    <Link
                      href={project.link}
                      target="_blank"
                      rel="noreferrer"
                      className="hover:cursor-pointer "
                    >
                      DEMO
                    </Link>
                  </div>
                  {project.repo ? (
                    <div className="badge badge-accent border border-primary mr-2 hover:border-secondary hover:scale-125">
                      {project.repo ? (
                        <>
                          <Link
                            href={project.repo}
                            target="_blank"
                            rel="noreferrer"
                            className="hover:cursor-pointer"
                          >
                            CODE
                          </Link>
                        </>
                      ) : null}
                    </div>
                  ) : (
                    ""
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Projects;
