import AboutMe from "../components/AboutMe";
import MyEducation from "../components/MyEducation";
import MyExperience from "../components/MyExperience";
import MyProjects from "../components/MyProjects";
import MySkills from "../components/MySkills";
import ResumeHeader from "../components/ResumeHeader";
import Head from "next/head";
import MySkillsTwo from "../components/MySkillTwo";
import { useEffect } from "react";
import { themeChange, themeSelect } from "theme-change";

const Resume = () => {
  useEffect(() => {
    themeChange(false);
    // false parameter is required for react project
  }, []);
  return (
    <>
      <Head>
        <title>DK | Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      {/* <!-- Page --> */}
      <div
        className="bg-repeat w-full h-full heropattern-topography-gray-300 p-5"
        data-theme="corporate"
      >
        <div
          className="font-serif mx-auto page max-w-4xl p-5
      md:max-w-letter md:h-letter xsm:p-8 sm:p-9 md:p-16 bg-gray-100 border-stone-900 rounded-lg border-4"
        >
          <ResumeHeader />
          {/* <!-- Column --> */}
          <div className="grid grid-cols-2 md:col-count-2 col-gap-md md:h-letter-col-full col-fill-auto">
            <AboutMe />
            <MyExperience />
            <MyEducation />
            <MyProjects />
            <MySkills />
            <MySkillsTwo />
          </div>

          {/* <!-- end Column --> */}
        </div>
        {/* <!-- end Page --> */}
      </div>
    </>
  );
};

export default Resume;
